---
namespace: fmjstudios
name: encryption
version: 0.0.1
readme: README.md
authors:
  - Maximilian Gindorfer <info@fmj.dev>
description: Ansible Collection for encryption and security (TLS, ssh, ..)
license_file: "LICENSE"
tags:
  - encryption
  - security
  - hardening
  - tls
  - ssl
  - ssh
dependencies:
  community.general: ">=7.1.0"
repository: http://example.com/repository
documentation: http://docs.example.com
homepage: https://fmj.dev
issues: http://example.com/issue/tracker
build_ignore:
  - .gitignore
  - LICENSE
  - Makefile
  - AUTHORS
  - .vscode
  - .github