---
- name: Preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
    apply:
      tags:
        - certbot_install
        - certbot_configure
        - certbot_run
  tags:
    - certbot_install
    - certbot_configure
    - certbot_run

- name: Install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      become: true
      tags:
        - certbot_install
  tags:
    - certbot_install

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      become: true
      tags:
        - certbot_configure
  tags:
    - certbot_configure
