---
- name: Preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
    apply:
      tags:
        - lego_install
        - lego_configure
        - lego_run
  tags:
    - lego_install
    - lego_configure
    - lego_run

- name: Install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      become: true
      tags:
        - lego_install
  tags:
    - lego_install

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      become: true
      tags:
        - lego_configure
  tags:
    - lego_configure

- name: Ensure Go Lego service is started and enabled
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ lego_systemd_service }}"
    state: started
    enabled: true

- name: Flush handlers after run.
  ansible.builtin.meta: flush_handlers
